create extension if not exists "pg_cron" with schema "extensions";

drop extension if exists "pg_net";


  create table "public"."courses" (
    "title" text not null default ''::text,
    "description" text default ''::text,
    "start_datetime" timestamp with time zone not null,
    "end_datetime" timestamp with time zone not null,
    "group" text not null,
    "_professors" json not null default '[]'::json,
    "location" text,
    "created_at" timestamp with time zone default now(),
    "id" uuid not null default gen_random_uuid(),
    "disabled" boolean not null default false,
    "professors" text[]
      );


alter table "public"."courses" enable row level security;


  create table "public"."grades" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "label" text not null,
    "code" text not null,
    "ue" text not null,
    "code_ue" text not null,
    "coef" smallint not null,
    "mean" double precision,
    "credits" text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."grades" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null default gen_random_uuid(),
    "email" text,
    "role" text default 'USER'::text,
    "created_at" timestamp with time zone default now(),
    "alcuin_password" text,
    "path_name" text,
    "available_path_names" text[],
    "groups" text[] not null default '{}'::text[]
      );


alter table "public"."profiles" enable row level security;


  create table "public"."queue" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "command" text not null,
    "created_at" timestamp with time zone not null default now(),
    "finished" boolean not null default false,
    "message" text
      );


alter table "public"."queue" enable row level security;

CREATE UNIQUE INDEX courses_pkey ON public.courses USING btree (id);

CREATE UNIQUE INDEX grades_pkey ON public.grades USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX queue_pkey ON public.queue USING btree (id);

alter table "public"."courses" add constraint "courses_pkey" PRIMARY KEY using index "courses_pkey";

alter table "public"."grades" add constraint "grades_pkey" PRIMARY KEY using index "grades_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."queue" add constraint "queue_pkey" PRIMARY KEY using index "queue_pkey";

alter table "public"."grades" add constraint "grades_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."grades" validate constraint "grades_user_id_fkey";

alter table "public"."queue" add constraint "queue_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."queue" validate constraint "queue_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_professors()
 RETURNS SETOF text
 LANGUAGE plpgsql
AS $function$
DECLARE
    value text;
BEGIN
    -- Use UNNEST and DISTINCT to get distinct unnested values from the array column
    FOR value IN SELECT DISTINCT unnest(professors) FROM courses
    LOOP
        -- Return each distinct unnested value
        RETURN NEXT value;
    END LOOP;

    RETURN;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_old_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  delete from public.profiles where id=old.id;
  return old;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_update_profile()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$begin
  if (new.alcuin_password != old.alcuin_password or old.alcuin_password is NULL) and new.alcuin_password != 'INVALID' and new.alcuin_password != '' and new.alcuin_password is not NULL then
    INSERT INTO queue (user_id, command, finished) VALUES (new.id, 'SCRAPE_PATH_NAMES', FALSE);
    new.available_path_names = NULL;
    new.path_name = NULL;
  end if;

  if (new.path_name != old.path_name or old.path_name is NULL) and new.path_name != 'INVALID' and new.path_name != '' and new.path_name is not NULL then
    INSERT INTO queue (user_id, command, finished) VALUES (new.id, 'SCRAPE_GRADES', FALSE);
  end if;

  return new;
end;$function$
;

CREATE OR REPLACE FUNCTION public.handle_update_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  update public.profiles set email=new.email where id=new.id;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.is_profile_admin(uid uuid)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN (( SELECT count(*) AS count
   FROM profiles profiles_1
  WHERE ((profiles_1.id = uid) AND (profiles_1.role = 'ADMIN'::text))) > 0);
END;
$function$
;


  create policy "Allow everything for service key"
  on "public"."courses"
  as permissive
  for all
  to service_role
using (true)
with check (true);



  create policy "Allow reads for authenticated"
  on "public"."courses"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Allow update for authentiated (TEMPORARY)"
  on "public"."courses"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Allow all "
  on "public"."grades"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "Allow all admin"
  on "public"."grades"
  as permissive
  for all
  to authenticated
using (is_profile_admin(auth.uid()))
with check (is_profile_admin(auth.uid()));



  create policy "Allow all service"
  on "public"."grades"
  as permissive
  for all
  to service_role
using (true)
with check (true);



  create policy "Allow select self"
  on "public"."grades"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "Allow all for admin"
  on "public"."profiles"
  as permissive
  for all
  to authenticated
using (is_profile_admin(auth.uid()))
with check (is_profile_admin(auth.uid()));



  create policy "Allow all for service"
  on "public"."profiles"
  as permissive
  for all
  to service_role
using (true)
with check (true);



  create policy "Allow self update"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((auth.uid() = id))
with check ((auth.uid() = id));



  create policy "Get own profile"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using ((auth.uid() = id));



  create policy "Allow all admins"
  on "public"."queue"
  as permissive
  for all
  to authenticated
using (is_profile_admin(auth.uid()))
with check (is_profile_admin(auth.uid()));



  create policy "Only Service "
  on "public"."queue"
  as permissive
  for all
  to service_role, pgsodium_keyholder, pgsodium_keyiduser, pgsodium_keymaker, supabase_replication_admin
using (true)
with check (true);


CREATE TRIGGER on_update_profile AFTER UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION handle_update_profile();

CREATE TRIGGER handle_new_user AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();

CREATE TRIGGER handle_old_user AFTER DELETE ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_old_user();

CREATE TRIGGER handle_update_user AFTER UPDATE ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_update_user();


